//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MordenDoors.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetToken
    {
        public int id { get; set; }
        public string clientid { get; set; }
        public string clientsecret { get; set; }
        public string realmId { get; set; }
        public string AccessToken { get; set; }
        public string AccessTokenExpiresIn { get; set; }
        public string RefreshToken { get; set; }
        public string RefreshTokenExpiresIn { get; set; }
    }
}
