//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MordenDoors.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string LegalName { get; set; }
        public string CompanyAddrId { get; set; }
        public string CompanyAddrLine1 { get; set; }
        public string CompanyAddrCity { get; set; }
        public string CompanyAddrCountry { get; set; }
        public string CompanyAddrCountrySubDivisionCode { get; set; }
        public string CompanyAddrPostalCode { get; set; }
        public string CustomerCommunicationAddrId { get; set; }
        public string CustomerCommunicationAddrLine1 { get; set; }
        public string CustomerCommunicationAddrCity { get; set; }
        public string CustomerCommunicationAddrCountry { get; set; }
        public string CustomerCommunicationAddrCountrySubDivisionCode { get; set; }
        public string CustomerCommunicationAddrPostalCode { get; set; }
        public string LegalAddrId { get; set; }
        public string LegalAddrLine1 { get; set; }
        public string LegalAddrCity { get; set; }
        public string LegalAddrCountry { get; set; }
        public string LegalAddrCountrySubDivisionCode { get; set; }
        public string LegalAddrPostalCode { get; set; }
        public string PrimaryPhone { get; set; }
        public string SecondaryPhone { get; set; }
        public string PrimaryFax { get; set; }
        public string CompanyStartDate { get; set; }
        public string EmployerId { get; set; }
        public string FiscalYearStartMonth { get; set; }
        public string Country { get; set; }
        public string EmailAddress { get; set; }
        public string WebAddrURI { get; set; }
        public string CreateTime { get; set; }
        public string LastUpdatedTime { get; set; }
    }
}
