//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MordenDoors.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string GivenName { get; set; }
        public string FamilyName { get; set; }
        public string FullyQualifiedName { get; set; }
        public string DisplayName { get; set; }
        public string PrintOnCheckName { get; set; }
        public bool Active { get; set; }
        public string PrimaryPhone { get; set; }
        public string AlternatePhone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string DefaultTaxCodeRef { get; set; }
        public string time { get; set; }
        public string CreateTime { get; set; }
        public string LastUpdatedTime { get; set; }
        public string PreferredDeliveryMethod { get; set; }
        public string CurrencyRef { get; set; }
        public string Balance { get; set; }
        public string BalanceWithJobs { get; set; }
        public string Taxable { get; set; }
        public string BillAddrId { get; set; }
        public string BillAddrLine1 { get; set; }
        public string BillAddrLine2 { get; set; }
        public string BillAddrCity { get; set; }
        public string BillAddrCountry { get; set; }
        public string BillAddrCountrySubDivisionCode { get; set; }
        public string BillAddrPostalCode { get; set; }
        public string ShipAddrId { get; set; }
        public string ShipAddrLine1 { get; set; }
        public string ShipAddrLine2 { get; set; }
        public string ShipAddrCity { get; set; }
        public string ShipAddrCountry { get; set; }
        public string ShipAddrCountrySubDivisionCode { get; set; }
        public string ShipAddrPostalCode { get; set; }
        public string PrimaryEmailAddr { get; set; }
        public string ZohoContactId { get; set; }
        public Nullable<int> CreditLimit { get; set; }
    }
}
