//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MordenDoors.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPrice
    {
        public int ID { get; set; }
        public int CustomerId { get; set; }
        public int CategoryId { get; set; }
        public int ProductId { get; set; }
        public decimal Price { get; set; }
    }
}
