//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MordenDoors.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operations
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int WorkcentreId { get; set; }
        public Nullable<System.DateTime> ReleasedDate { get; set; }
        public Nullable<int> TotalQty { get; set; }
        public Nullable<float> TotalSqft { get; set; }
        public Nullable<int> QtyDone { get; set; }
        public Nullable<float> SqftDone { get; set; }
        public Nullable<int> QtyRemaining { get; set; }
        public Nullable<float> SqftRemaining { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public Nullable<int> TotalTime { get; set; }
        public Nullable<int> AllocatedTime { get; set; }
        public string EmployeeId { get; set; }
        public bool IsComplete { get; set; }
        public Nullable<int> OrderItem { get; set; }
        public Nullable<byte> Sort { get; set; }
        public bool isGet { get; set; }
        public bool IsCompleted { get; set; }
        public string Location { get; set; }
    }
}
