//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MordenDoors.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMaster
    {
        public int OrderID { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerPo { get; set; }
        public string CustomerRef { get; set; }
        public string Comments { get; set; }
        public Nullable<int> ShipVia { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<float> SubTotal { get; set; }
        public Nullable<float> Gst { get; set; }
        public Nullable<float> Pst { get; set; }
        public Nullable<float> Total { get; set; }
        public Nullable<float> FreightCost { get; set; }
        public Nullable<float> ShippingCharge { get; set; }
        public Nullable<int> TotalDoors { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool Acknowledged { get; set; }
        public Nullable<int> Status { get; set; }
        public bool IsQuote { get; set; }
        public string QuoteNo { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<float> TotalSqft { get; set; }
        public Nullable<bool> IsSentToShop { get; set; }
        public Nullable<System.DateTime> SentToShopDate { get; set; }
        public bool IsReady { get; set; }
        public Nullable<System.DateTime> ReadyDate { get; set; }
        public bool IsInvoiced { get; set; }
        public string InvoiceId { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
    }
}
