//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MordenDoors.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public decimal TotalAmount { get; set; }
        public string Comments { get; set; }
        public int StatusId { get; set; }
        public bool PaymentComplete { get; set; }
        public System.DateTime CretaedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string InvoiceId { get; set; }
        public string TrackingID { get; set; }
        public System.DateTime DeliveryTime { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string PinCode { get; set; }
        public string PO { get; set; }
        public string Job { get; set; }
        public Nullable<decimal> customerprice { get; set; }
        public Nullable<decimal> PayableAmount { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<decimal> PST { get; set; }
        public string ExtrnalId { get; set; }
    }
}
