//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MordenDoors.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatus
    {
        public int Id { get; set; }
        public string orderStatus1 { get; set; }
        public Nullable<byte> sortKey { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
