//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MordenDoors.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItemList
    {
        public int Id { get; set; }
        public Nullable<int> OrderItemId { get; set; }
        public string Category { get; set; }
        public string Product { get; set; }
    }
}
