//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MordenDoors.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductWorkstages
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string RoleId { get; set; }
        public Nullable<byte> Sort { get; set; }
    }
}
