//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MordenDoors.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncSettings
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string accesstoken { get; set; }
        public string refreshtoken { get; set; }
        public Nullable<System.DateTime> expiredon { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
    }
}
