//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MordenDoors.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitsOfMeasure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnitsOfMeasure()
        {
            this.Products = new HashSet<Products>();
            this.Products1 = new HashSet<Products>();
        }
    
        public int UnitID { get; set; }
        public string UnitName { get; set; }
        public string UnitDescription { get; set; }
        public bool IsActive { get; set; }
        public bool HasHeight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products1 { get; set; }
        public virtual UnitsOfMeasure UnitsOfMeasure1 { get; set; }
        public virtual UnitsOfMeasure UnitsOfMeasure2 { get; set; }
    }
}
